package com.fei2e.getlost.entity;

import javax.persistence.*;

@Table(name = "`dictionary`")
public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.region_code
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.region_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.region_name_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String regionNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.region_shortname_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String regionShortnameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.fid
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.level
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Byte level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.region_code
     *
     * @return the value of dictionary.region_code
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.region_code
     *
     * @param regionCode the value for dictionary.region_code
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.region_name
     *
     * @return the value of dictionary.region_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.region_name
     *
     * @param regionName the value for dictionary.region_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.region_name_en
     *
     * @return the value of dictionary.region_name_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getRegionNameEn() {
        return regionNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.region_name_en
     *
     * @param regionNameEn the value for dictionary.region_name_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setRegionNameEn(String regionNameEn) {
        this.regionNameEn = regionNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.region_shortname_en
     *
     * @return the value of dictionary.region_shortname_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getRegionShortnameEn() {
        return regionShortnameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.region_shortname_en
     *
     * @param regionShortnameEn the value for dictionary.region_shortname_en
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setRegionShortnameEn(String regionShortnameEn) {
        this.regionShortnameEn = regionShortnameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.fid
     *
     * @return the value of dictionary.fid
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.fid
     *
     * @param fid the value for dictionary.fid
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.level
     *
     * @return the value of dictionary.level
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.level
     *
     * @param level the value for dictionary.level
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLevel(Byte level) {
        this.level = level;
    }
}