package com.fei2e.getlost.entity;

import javax.persistence.*;

@Table(name = "`get_tag_ref`")
public class GetTagRef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_tag_ref.get_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer getId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer dictId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_tag_ref.tag_id
     *
     * @return the value of get_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_tag_ref.tag_id
     *
     * @param tagId the value for get_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_tag_ref.get_id
     *
     * @return the value of get_tag_ref.get_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getGetId() {
        return getId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_tag_ref.get_id
     *
     * @param getId the value for get_tag_ref.get_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setGetId(Integer getId) {
        this.getId = getId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_tag_ref.dict_id
     *
     * @return the value of get_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_tag_ref.dict_id
     *
     * @param dictId the value for get_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }
}