package com.fei2e.getlost.entity;

import javax.persistence.*;

@Table(name = "`goods_extra`")
public class GoodsExtra {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_extra.extral_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer extralId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_extra.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_extra.field_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_extra.field_value
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String fieldValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_extra.extral_id
     *
     * @return the value of goods_extra.extral_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getExtralId() {
        return extralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_extra.extral_id
     *
     * @param extralId the value for goods_extra.extral_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setExtralId(Integer extralId) {
        this.extralId = extralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_extra.goods_id
     *
     * @return the value of goods_extra.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_extra.goods_id
     *
     * @param goodsId the value for goods_extra.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_extra.field_name
     *
     * @return the value of goods_extra.field_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_extra.field_name
     *
     * @param fieldName the value for goods_extra.field_name
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_extra.field_value
     *
     * @return the value of goods_extra.field_value
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_extra.field_value
     *
     * @param fieldValue the value for goods_extra.field_value
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }
}