package com.fei2e.getlost.entity;

import javax.persistence.*;

@Table(name = "`lost_tag_ref`")
public class LostTagRef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_tag_ref.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer lostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer dictId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_tag_ref.tag_id
     *
     * @return the value of lost_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_tag_ref.tag_id
     *
     * @param tagId the value for lost_tag_ref.tag_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_tag_ref.lost_id
     *
     * @return the value of lost_tag_ref.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getLostId() {
        return lostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_tag_ref.lost_id
     *
     * @param lostId the value for lost_tag_ref.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLostId(Integer lostId) {
        this.lostId = lostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_tag_ref.dict_id
     *
     * @return the value of lost_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_tag_ref.dict_id
     *
     * @param dictId the value for lost_tag_ref.dict_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }
}