package com.fei2e.getlost.entity;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "`position`")
public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.lng
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private BigDecimal lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.lat
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.address
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_id
     *
     * @return the value of position.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_id
     *
     * @param positionId the value for position.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.lng
     *
     * @return the value of position.lng
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.lng
     *
     * @param lng the value for position.lng
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.lat
     *
     * @return the value of position.lat
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.lat
     *
     * @param lat the value for position.lat
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.address
     *
     * @return the value of position.address
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.address
     *
     * @param address the value for position.address
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }
}