package com.fei2e.getlost.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`up_lost`")
public class UpLost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer lostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.user_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.title
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.content
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.lost_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Date lostTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.create_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.creator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.operator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.operate_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_lost.telephone
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.lost_id
     *
     * @return the value of up_lost.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getLostId() {
        return lostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.lost_id
     *
     * @param lostId the value for up_lost.lost_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLostId(Integer lostId) {
        this.lostId = lostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.user_id
     *
     * @return the value of up_lost.user_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.user_id
     *
     * @param userId the value for up_lost.user_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.goods_id
     *
     * @return the value of up_lost.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.goods_id
     *
     * @param goodsId the value for up_lost.goods_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.position_id
     *
     * @return the value of up_lost.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.position_id
     *
     * @param positionId the value for up_lost.position_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.title
     *
     * @return the value of up_lost.title
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.title
     *
     * @param title the value for up_lost.title
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.content
     *
     * @return the value of up_lost.content
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.content
     *
     * @param content the value for up_lost.content
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.lost_time
     *
     * @return the value of up_lost.lost_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Date getLostTime() {
        return lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.lost_time
     *
     * @param lostTime the value for up_lost.lost_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setLostTime(Date lostTime) {
        this.lostTime = lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.create_time
     *
     * @return the value of up_lost.create_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.create_time
     *
     * @param createTime the value for up_lost.create_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.creator_id
     *
     * @return the value of up_lost.creator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.creator_id
     *
     * @param creatorId the value for up_lost.creator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.operator_id
     *
     * @return the value of up_lost.operator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.operator_id
     *
     * @param operatorId the value for up_lost.operator_id
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.operate_time
     *
     * @return the value of up_lost.operate_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.operate_time
     *
     * @param operateTime the value for up_lost.operate_time
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_lost.telephone
     *
     * @return the value of up_lost.telephone
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_lost.telephone
     *
     * @param telephone the value for up_lost.telephone
     *
     * @mbggenerated Mon Sep 28 17:24:23 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
}